In [ ]:
import numpy as np
import pandas as pd
from sklearn import tree
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet,LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.tree import DecisionTreeClassifier,plot_tree
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.naive_bayes import CategoricalNB #categorical handle discrete value like (color,level etc)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report,mean_squared_error
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from matplotlib.pyplot import figure
from sklearn.svm import SVC
from sklearn.svm import SVR
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.multioutput import MultiOutputClassifier
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/Rand of ALL Cross Dataset with URLs.csv', encoding='utf-8')
df.sample(5)

,url,headline,Language,Text,Translated_Text,Domain,Domain_ID,Translated_Domain,Translated_Domain_ID,Sub-Domain,Sub-Domain_ID,Translated_Sub-Domain,Translated_Sub-Domain_ID
1828,https://www.prothomalo.com/entertainment/world...,যৌন হয়রানির বিচার চাইতে গিয়ে যেভাবে পরিচালক হয়...,bn,নোরিয়ুকি ইয়ামাগুচি। জাপানের প্রভাবশালী এক সাংব...,Noriyuki Yamaguchi. An influential journalist ...,বিনোদন,2,Entertainment,2,সিনেমা,8,Movie,8
394,https://www.thedailystar.net/entertainment/mus...,Runa Laila’s song inspires endangered Indian t...,en,"In Totopara, a small village on the Bhutan bor...",পশ্চিমবঙ্গের আলিপুরদুয়ার জেলার ভুটান সীমান্তে...,Entertainment,2,বিনোদন,2,Music,7,সঙ্গীত,7
4281,https://www.prothomalo.com/entertainment/world...,"কে–পপ তারকার আত্মহত্যার চেষ্টা, এখনো জ্ঞান ফেরেনি",bn,আত্মহত্যার চেষ্টার পর কে–পপ তারকা লি আরিয়মকে হ...,K-pop star Lee Ariem has been hospitalized aft...,বিনোদন,2,Entertainment,2,সিনেমা,8,Movie,8
4139,NaN,NaN,en,"Athletes are often cast as entertainers, their...",ক্রীড়াবিদদের প্রায়শই বিনোদনদাতা হিসেবে দেখা ...,Sports,0,খেলাধুলা,0,Tennis,2,টেনিস,2
2932,https://www.prothomalo.com/bangladesh/crime/fo...,বাড্ডায় যুবকের গুলিবিদ্ধ মরদেহ উদ্ধার,bn,রাজধানীর মধ্য বাড্ডা এলাকার কমিশনার গলির একটি ...,Police have recovered the bullet-riddled body ...,অপরাধ,1,Crime,1,সহিংস অপরাধ,3,Violent crime,3

In [ ]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.16.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.1)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# Prepare nlp_df
nlp_df = df.copy()

# 1. Directly use 'Domain_ID' as our numerical target
y_domain_numerical = nlp_df['Domain_ID'].astype(int)

# 2. Define X_domain as the 'Text' column from nlp_df
X_domain = nlp_df['Text'].str.strip()

# 3. Split into 80% Train and 20% Temporary (Validation + Test)
X_train_domain, X_temp_domain, y_train_domain, y_temp_domain = train_test_split(
    X_domain, y_domain_numerical, test_size=0.2, random_state=42, stratify=y_domain_numerical
)

# 4. Split the 20% temporary set equally (50% each) to get exactly 10% Validation and 10% Test
X_val_domain, X_test_domain, y_val_domain, y_test_domain = train_test_split(
    X_temp_domain, y_temp_domain, test_size=0.5, random_state=42, stratify=y_temp_domain
)

# 5. Print the shapes of the resulting datasets
print(f"Shape of X_train_domain: {X_train_domain.shape} (80%)")
print(f"Shape of y_train_domain: {y_train_domain.shape}")
print(f"Shape of X_val_domain: {X_val_domain.shape} (10%)")
print(f"Shape of y_val_domain: {y_val_domain.shape}")
print(f"Shape of X_test_domain: {X_test_domain.shape} (10%)")
print(f"Shape of y_test_domain: {y_test_domain.shape}")

# 6. Print sample numerical labels from y_train_domain
print(f"\nSample of y_train_domain: {y_train_domain[:5].tolist()}")

Shape of X_train_domain: (8745,) (80%)
Shape of y_train_domain: (8745,)
Shape of X_val_domain: (1093,) (10%)
Shape of y_val_domain: (1093,)
Shape of X_test_domain: (1094,) (10%)
Shape of y_test_domain: (1094,)

Sample of y_train_domain: [4, 1, 3, 2, 4]

In [ ]:
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict

# Ensure X_train_domain, y_train_domain, X_val_domain, y_val_domain, X_test_domain, y_test_domain are defined.
# These should have been set up by cell '1595d2c3' and are available in the environment.

# Define MAX_LENGTH for tokenization (reusing the value from previous cells)
MAX_LENGTH_DOMAIN = 256 # A common length for BERT models

# 1. Define the model name for xlm-roberta
xlm_roberta_domain_model_name = 'xlm-roberta-base'

# 2. Load the tokenizer for the xlm-roberta model
xlm_roberta_domain_tokenizer = AutoTokenizer.from_pretrained(xlm_roberta_domain_model_name)

# 3. Create a DatasetDict containing 'train', 'validation', and 'test' datasets
dataset_dict_domain_xlm_roberta = DatasetDict({
    'train': Dataset.from_dict({
        'text': X_train_domain.tolist(),
        'label': y_train_domain.tolist()
    }),
    'validation': Dataset.from_dict({
        'text': X_val_domain.tolist(),
        'label': y_val_domain.tolist()
    }),
    'test': Dataset.from_dict({
        'text': X_test_domain.tolist(),
        'label': y_test_domain.tolist()
    })
})

# 4. Create a tokenization function
def tokenize_function_xlm_roberta_domain(examples):
    tokenized_inputs = xlm_roberta_domain_tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=MAX_LENGTH_DOMAIN
    )
    tokenized_inputs['labels'] = examples['label'] # Ensure 'labels' key is present
    return tokenized_inputs

# 5. Apply this tokenization function to all datasets
processed_datasets_xlm_roberta_domain = dataset_dict_domain_xlm_roberta.map(tokenize_function_xlm_roberta_domain, batched=True)

# 6. Set the format of the processed datasets to 'torch'
processed_datasets_xlm_roberta_domain.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

print("XLM-RoBERTa Tokenizer loaded and 'Domain' data processed.")
print(f"Sample of processed_datasets_xlm_roberta_domain['train'][0]: {processed_datasets_xlm_roberta_domain['train'][0]}")
print(f"Sample of processed_datasets_xlm_roberta_domain['validation'][0]: {processed_datasets_xlm_roberta_domain['validation'][0]}")
print(f"Sample of processed_datasets_xlm_roberta_domain['test'][0]: {processed_datasets_xlm_roberta_domain['test'][0]}")

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

Map:   0%|          | 0/8745 [00:00<?, ? examples/s]

Map:   0%|          | 0/1093 [00:00<?, ? examples/s]

Map:   0%|          | 0/1094 [00:00<?, ? examples/s]

XLM-RoBERTa Tokenizer loaded and 'Domain' data processed.
Sample of processed_datasets_xlm_roberta_domain['train'][0]: {'input_ids': tensor([     0,  73078, 122305, 104216,   9618,  69057,   5507,  63094, 209423,
          4557,      6, 112542,  13327,  44672,  66106, 116605,   2763, 176842,
         32368, 110362, 213065,      6, 112542,  13327,  44672,  66106, 116605,
          2763, 169720,  42579,  72999,  28746, 154485,    125,   6386, 170478,
         72229,      6, 104694,  86443,  87084, 206912,  61705,    896,   4691,
        125902,    999, 170812,  77162,  41450, 170045,   4557,    125,  25508,
         97457, 187909, 200966,   2784,  95085,  16550,   4979, 221461,   8339,
         19368, 122948,    956,   4577, 170812,  77162,   7185,   9681,    125,
        136729,      6, 222056, 148264, 161277, 170045,  64123,   4979,  10062,
         34510,  13327,   2784,      6,  17891, 178894, 184515, 119977,    125,
          4577,  20895, 170045,    896,  52431, 215840,    999,  57871,   5534,
        141724, 118821,    125,  19368, 122948,    956, 204719,   9681,      4,
         61705,    896,   4691,   4876, 170812, 194879,    896,   8619,      6,
        112542,  13327,  44672,  69057,   2114, 169555,   9307,  30511,  66106,
          9078, 236456,    999,      6, 100456,  86443,  68301, 187531, 170812,
        128866,   7185,   9591,    125, 170812,  77162,   5507,      6,  17891,
        178894, 184515, 119977,  66594,      4,  11785,  31636,  32427, 129405,
        119226,  55141,    956,  28746,  68088, 216486,    999,  40257,   8099,
         28746, 164533, 242731,    896,  57871,   5521,  23304,  48285, 220958,
        237925,  74665,   2145,  25690,  95719,  16908, 109442,  86260,  20895,
         89217, 199112,    896, 226256,  69057, 209423,   4557,  66106, 116605,
          2763, 236828,   5507,  64789,   2145,    999,  13327, 176842,    999,
        138867, 175310,    125,  97393,   8339, 209190,   4691,  46085,    896,
         63980,  66106, 116605,   2763, 209423,   4557, 176842,  32368,  77162,
        173989,    125,  46729,  66468, 206912,   6638,  10947,   5534, 137996,
          4480,  28856,      6, 138463,   7212,  34523,   4979,  15314,   9853,
         23703,   2730, 160542, 229951, 121176,    999, 127274,   6155,  63094,
          9681,    125,      2,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(4)}
Sample of processed_datasets_xlm_roberta_domain['validation'][0]: {'input_ids': tensor([     0, 235326,    896,   6334,  19418,   2801,  87045,    956,  16209,
         62759,    896,  20895,      6, 233339,  10947, 103872, 100859,      6,
         62873,  29881, 175126,   7185,  13171,    125,   4577,  20895,  52553,
         91661,   2937,  28445, 151801, 209979,   7443,  68927,    896, 217647,
         63094,  13171,    125, 135361,  19039,  51538, 175544,   2801, 214528,
        205249, 154831,  54682, 128357,   4198,  10413,   9853,  13880, 147294,
         13413,  36539,  19293,   2784, 175142, 103498, 230883,   4577,      6,
         62873,  29881, 175126,   8099,  16908,  20184, 161277,    125,  29881,
        175126,   7185,  16908,  70904,  21387,  48578,      6,  95246,  10947,
        103872,  44911,  28217,  21820,     15, 140102,   2730,   1104,  44993,
         14329,  38691,   2145, 212068,  22741,   3458,  66272,   5780,     16,
          8099,  37783,  10947, 103872,  74665, 122187,    125, 235326,    896,
          6334,  19418,   2801,  87045,  51001, 151462, 218036,     15, 180998,
            16,   4979, 109548,  20256, 199171,  10947,  93004, 103498, 208728,
         33619,    125,  54682, 128357,   4198,  10413,   9853,  13880, 147294,
        171911,  47301,   2801,      4, 227173,  19368,    896, 210398,   3495,
        214528, 124751,  39267,  58065,  96242,  54682, 128357,   4198,  10413,
          9853,  13880, 147294, 135361,  19039,  51538, 175544, 209444,  31797,
         62820, 153634, 103498, 230883,  22540,  38084,   2145,   6638,  47448,
        101127,  34483, 207968,   7277,  17063, 234807,    999,  37783,  10947,
        103872,  74665, 122187,      6,  62873,  52553,  33619,    125, 207043,
        124751, 180153,  39267,  58065,  96242,  54682, 128357,   4198,  10413,
          9853,  13880, 147294, 103498, 230883, 135361,  19039,  51538, 175544,
          2801, 216907,  17455,  77065,    999,  22853,  24845, 153634,  10814,
         66519,  55820,  58798,   2763,  12468,  54682,   5780,  19418,   4557,
         90862, 161347,  35312,   7277,  28217,  28555, 137609,      6,  95246,
         10947, 103872,  44911,  28217,  21820,      6,  62873,  52553,  33619,
           125,  95956,      6,  62873,  13705,   9078, 117848,  24373,  51001,
          6638,  19039,  51538,      2]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 'labels': tensor(3)}
Sample of processed_datasets_xlm_roberta_domain['test'][0]: {'input_ids': tensor([     0, 227935,    896, 101311,    956, 132609,  24373,  43875,  51538,
          2763,  28746,  16447,   7443, 108798, 153634,  18780,      9,  65724,
         84264, 141894,  10062,  76770,   3458,  24845,  75011,  16209,   8377,
          6638,  14536, 198048,  21431,  15541,  89218,  41450,      6,  70313,
         28145,    125,  25508,  86442, 167985, 101311,    956, 132609,  24373,
         43875,  51538,   2763,  28746, 115199, 128032,  31938,  21841, 168949,
         26020,  85181, 153634,  91866,  37380,  13705,    999,  47458,  10062,
         91605, 199238,  27861, 102943, 192698, 125079,      6,  70313,  99324,
         53509,   5534,    125,  10947,  96427, 133065,   4091,   2114, 240178,
          4822,  54546, 121542,  10413,  42579,    999, 107291,  53509,  72238,
          9115,  16576,  28680,  24090,      4,    204,  31704,   8276, 167985,
         43875,  51538,   2763,  28746, 115199, 128032,  31938,  53509,      9,
        211386,   5534,  76770,   3458,  24845,  75011, 181432,  91866,  37380,
         13705,    999,  47458,  10062,  91605, 170307, 104157,  23456, 178090,
         66594,    125,  17830,  38841, 107291,   9976,  25518, 178090,      6,
        244865,  10567,  22349,  34510,  86492,  53509,   5521, 204719,   9681,
           125,  97393,  44922,    956,  27861,  63094,  13171,    125,  74252,
         38540,   9618, 157625, 129451, 172795,      4, 198048,  91866,  37380,
        150800,   2801,      6,  11984,   3397,  86493,  10062,   7212,   2145,
         33338,      4,  60910,  11291,   3397,  34653,  80936,  21264, 166349,
         13171,  40966,   6386,  53509,  24090,      4,  10814,  15541,   4198,
         22349, 170579, 107741,  14536,  22741,  20423,   2145,   3458,   9976,
         34916,   4198,  74252,  38540,  74551, 115199,  46085,    956,  25792,
          4876,   6155, 173427,    125, 227935,  19150,   5780, 174451,   7498,
         13134, 139313, 107741, 132133, 204915,  44922,   2114,      6,  65935,
         20824,  31797, 107741,  34916,   4198,  74252,  38540,   9618,  33338,
           125, 107741,  22741,  20423,   2145,   3458,   9976,  34916,   4198,
         27371, 163921,    896,  17589, 123258, 114442,  55820, 131255,  16908,
         10567,  20285,   2114,      2]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 'labels': tensor(3)}

##Domain Parameters

In [ ]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer
import torch
import gc

# --- Start: Ensure nlp_df and domain classification data are prepared ---
nlp_df = df.copy()

y_domain_numerical = nlp_df['Domain_ID'].astype(int)
X_domain = nlp_df['Text'].str.strip() #+ ' ' + nlp_df['Translated_Text'] # Handle potential NaN values in text

# Split X_domain and y_domain_numerical
X_train_domain, X_temp_domain, y_train_domain, y_temp_domain = train_test_split(
    X_domain, y_domain_numerical, test_size=0.2, random_state=42, stratify=y_domain_numerical
)

X_val_domain, X_test_domain, y_val_domain, y_test_domain = train_test_split(
    X_temp_domain, y_temp_domain, test_size=0.5, random_state=42, stratify=y_temp_domain
)

MAX_LENGTH_DOMAIN = 256
xlm_roberta_domain_model_name = 'xlm-roberta-base'
xlm_roberta_domain_tokenizer = AutoTokenizer.from_pretrained(xlm_roberta_domain_model_name)

dataset_dict_domain_xlm_roberta = DatasetDict({
    'train': Dataset.from_dict({
        'text': X_train_domain.tolist(),
        'label': y_train_domain.tolist()
    }),
    'validation': Dataset.from_dict({
        'text': X_val_domain.tolist(),
        'label': y_val_domain.tolist()
    }),
    'test': Dataset.from_dict({
        'text': X_test_domain.tolist(),
        'label': y_test_domain.tolist()
    })
})

def tokenize_function_xlm_roberta_domain(examples):
    tokenized_inputs = xlm_roberta_domain_tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=MAX_LENGTH_DOMAIN
    )
    tokenized_inputs['labels'] = examples['label']
    return tokenized_inputs

processed_datasets_xlm_roberta_domain = dataset_dict_domain_xlm_roberta.map(tokenize_function_xlm_roberta_domain, batched=True)
processed_datasets_xlm_roberta_domain.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
# --- End: Ensure nlp_df and domain classification data are prepared ---

# 1. Get number of unique labels for the model's output layer for 'Domain' classification
num_labels_domain = int(y_domain_numerical.nunique())
print(f"Number of unique labels for Domain classification: {num_labels_domain}")

# --- Memory Cleanup ---
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# 2. Load the pre-trained XLM-RoBERTa model for sequence classification
xlm_roberta_domain_model = AutoModelForSequenceClassification.from_pretrained(
    xlm_roberta_domain_model_name,
    num_labels=num_labels_domain
)
print(f"Model '{xlm_roberta_domain_model_name}' loaded for Domain classification.")

# 3. Define evaluation metrics
def compute_metrics(eval_pred):
    labels = eval_pred.label_ids
    preds = eval_pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro', zero_division=0)
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Check if CUDA (GPU) is available for training
use_cuda = torch.cuda.is_available()
print(f"Using CUDA (GPU) for training: {use_cuda}")

# 4. Configure training arguments for Domain classification with optimized memory parameters
training_args_xlm_roberta_domain = TrainingArguments(
    output_dir='./results_xlm_roberta_domain',
    num_train_epochs=5,
    per_device_train_batch_size=16,         # Increased for L4 GPU
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    learning_rate=2e-5,                     # Added learning rate
    # logging_dir='./logs_xlm_roberta_domain',
    logging_steps=10,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    fp16=use_cuda,                           # Enable mixed precision only if GPU is available
    report_to='none'
)

# 5. Initialize the Trainer for Domain classification
trainer_xlm_roberta_domain = Trainer(
    model=xlm_roberta_domain_model,
    args=training_args_xlm_roberta_domain,
    train_dataset=processed_datasets_xlm_roberta_domain['train'],
    eval_dataset=processed_datasets_xlm_roberta_domain['validation'],
    compute_metrics=compute_metrics
)

print("Trainer initialized for XLM-RoBERTa Domain classification.")

# 6. Train the model
trainer_xlm_roberta_domain.train()

print("XLM-RoBERTa Domain classification training complete. Evaluating model on the test set.")

# 7. Evaluate the model on the test set
results_xlm_roberta_domain = trainer_xlm_roberta_domain.evaluate(processed_datasets_xlm_roberta_domain['test'])

print("XLM-RoBERTa Domain classification Test set evaluation results:")
for key, value in results_xlm_roberta_domain.items():
    print(f"  {key}: {value:.4f}")

# 8. Create a pandas DataFrame for XLM-RoBERTa's Domain classification metrics
xlm_roberta_domain_metrics_data = {
    'Model': ['XLM-RoBERTa(Domain_Flat)'],
    'Accuracy': [results_xlm_roberta_domain['eval_accuracy']],
    'Precision (Macro Avg)': [results_xlm_roberta_domain['eval_precision']],
    'Recall (Macro Avg)': [results_xlm_roberta_domain['eval_recall']],
    'F1-Score (Macro Avg)': [results_xlm_roberta_domain['eval_f1']]
}
xlm_roberta_domain_metrics_df = pd.DataFrame(xlm_roberta_domain_metrics_data)

# 9. Display the xlm_roberta_domain_metrics_df DataFrame
display(xlm_roberta_domain_metrics_df)

Map:   0%|          | 0/8745 [00:00<?, ? examples/s]

Map:   0%|          | 0/1093 [00:00<?, ? examples/s]

Map:   0%|          | 0/1094 [00:00<?, ? examples/s]

Number of unique labels for Domain classification: 5

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.12GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model 'xlm-roberta-base' loaded for Domain classification.
Using CUDA (GPU) for training: True
Trainer initialized for XLM-RoBERTa Domain classification.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

XLM-RoBERTa Domain classification training complete. Evaluating model on the test set.

XLM-RoBERTa Domain classification Test set evaluation results:
  eval_loss: 0.2198
  eval_accuracy: 0.9534
  eval_f1: 0.9529
  eval_precision: 0.9522
  eval_recall: 0.9543

,Model,Accuracy,Precision (Macro Avg),Recall (Macro Avg),F1-Score (Macro Avg)
0,XLM-RoBERTa(Domain_Flat),0.953382,0.952234,0.954269,0.952851

In [ ]:
# import torch
# import numpy as np

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# # Ensure mapping dictionaries are defined
# domain_id_to_name = nlp_df.set_index('Domain_ID')['Domain'].drop_duplicates().to_dict()
# sub_domain_id_to_name = nlp_df.set_index('Sub-Domain_ID')['Sub-Domain'].drop_duplicates().to_dict()

# xlm_roberta_domain_model.to(device)
# xlm_roberta_domain_model.eval()

# predicted_domains = []

# for _, row in nlp_df.iterrows():

#     text = str(row['Text']) if pd.notna(row['Text']) else ''
#     translated_text = str(row['Translated_Text']) if pd.notna(row['Translated_Text']) else ''

#     combined_text = text + ' ' + translated_text

#     inputs = xlm_roberta_domain_tokenizer(
#         combined_text,
#         truncation=True,
#         padding='max_length',
#         max_length=MAX_LENGTH_DOMAIN,
#         return_tensors='pt'
#     )

#     inputs = {k: v.to(device) for k, v in inputs.items()}

#     with torch.no_grad():
#         outputs = xlm_roberta_domain_model(**inputs)

#     predicted_id = torch.argmax(outputs.logits, dim=-1).item()

#     predicted_domain = domain_id_to_name.get(
#         predicted_id,
#         "Unknown Domain"
#     )

#     predicted_domains.append(predicted_domain)

# nlp_df['Predicted_Domain'] = predicted_domains

#Sub-Dmain

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# 1. Directly use 'Sub-Domain_ID' as our numerical target
y_sub_domain_numerical = nlp_df['Sub-Domain_ID'].astype(int)

# 2. Define X_sub_domain as the concatenation of 'Domain' and 'Text'
X_sub_domain = nlp_df['Text'].fillna('').astype(str) #(nlp_df['Domain'].fillna('').astype(str) + " " +

# 3. Split into 80% Train and 20% Temporary (Validation + Test)
X_train_sub_domain, X_temp_sub_domain, y_train_sub_domain, y_temp_sub_domain = train_test_split(
    X_sub_domain, y_sub_domain_numerical, test_size=0.2, random_state=42, stratify=y_sub_domain_numerical
)

# 4. Split the 20% temporary set equally (50% each) to get exactly 10% Validation and 10% Test
X_val_sub_domain, X_test_sub_domain, y_val_sub_domain, y_test_sub_domain = train_test_split(
    X_temp_sub_domain, y_temp_sub_domain, test_size=0.5, random_state=42, stratify=y_temp_sub_domain
)

# 5. Print the shapes of the resulting datasets
print(f"Shape of X_train_sub_domain: {X_train_sub_domain.shape} (80%)")
print(f"Shape of y_train_sub_domain: {y_train_sub_domain.shape}")
print(f"Shape of X_val_sub_domain: {X_val_sub_domain.shape} (10%)")
print(f"Shape of y_val_sub_domain: {y_val_sub_domain.shape}")
print(f"Shape of X_test_sub_domain: {X_test_sub_domain.shape} (10%)")
print(f"Shape of y_test_sub_domain: {y_test_sub_domain.shape}")

# 6. Print sample numerical labels from y_train_sub_domain
print(f"\nSample of y_train_sub_domain: {y_train_sub_domain[:5].tolist()}")

Shape of X_train_sub_domain: (8745,) (80%)
Shape of y_train_sub_domain: (8745,)
Shape of X_val_sub_domain: (1093,) (10%)
Shape of y_val_sub_domain: (1093,)
Shape of X_test_sub_domain: (1094,) (10%)
Shape of y_test_sub_domain: (1094,)

Sample of y_train_sub_domain: [10, 11, 1, 6, 9]

In [ ]:
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict

# Ensure X_train_sub_domain, y_train_sub_domain, etc. are available from previous steps
# (specifically cell 'f3f3c2dc')

# Define MAX_LENGTH for tokenization (reusing the value from Domain classification)
MAX_LENGTH_SUB_DOMAIN = 512

# Prepare dataset_dict_sub_domain (if not already in scope from cell 72dbd092)
# Assuming X_train_sub_domain, y_train_sub_domain, etc. are populated.
dataset_dict_sub_domain_xlm_roberta = DatasetDict({
    'train': Dataset.from_dict({
        'text': X_train_sub_domain.tolist(),
        'label': y_train_sub_domain.tolist()
    }),
    'validation': Dataset.from_dict({
        'text': X_val_sub_domain.tolist(),
        'label': y_val_sub_domain.tolist()
    }),
    'test': Dataset.from_dict({
        'text': X_test_sub_domain.tolist(),
        'label': y_test_sub_domain.tolist()
    })
})

# 1. Define the model name for xlm-roberta
xlm_roberta_sub_domain_model_name = 'xlm-roberta-base'

# 2. Load the tokenizer for the xlm-roberta model
xlm_roberta_sub_domain_tokenizer = AutoTokenizer.from_pretrained(xlm_roberta_sub_domain_model_name)

# 3. Create a tokenization function
def tokenize_function_xlm_roberta_sub_domain(examples):
    tokenized_inputs = xlm_roberta_sub_domain_tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=MAX_LENGTH_SUB_DOMAIN
    )
    tokenized_inputs['labels'] = examples['label'] # Ensure 'labels' key is present
    return tokenized_inputs

# 4. Apply this tokenization function to all datasets
processed_datasets_xlm_roberta_sub_domain = dataset_dict_sub_domain_xlm_roberta.map(tokenize_function_xlm_roberta_sub_domain, batched=True)

# 5. Set the format of the processed datasets to 'torch'
processed_datasets_xlm_roberta_sub_domain.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

print("XLM-RoBERTa Tokenizer loaded and 'Sub-Domain' data processed.")
print(f"Sample of processed_datasets_xlm_roberta_sub_domain['train'][0]: {processed_datasets_xlm_roberta_sub_domain['train'][0]}")
print(f"Sample of processed_datasets_xlm_roberta_sub_domain['validation'][0]: {processed_datasets_xlm_roberta_sub_domain['validation'][0]}")
print(f"Sample of processed_datasets_xlm_roberta_sub_domain['test'][0]: {processed_datasets_xlm_roberta_sub_domain['test'][0]}")

Map:   0%|          | 0/8745 [00:00<?, ? examples/s]

Map:   0%|          | 0/1093 [00:00<?, ? examples/s]

Map:   0%|          | 0/1094 [00:00<?, ? examples/s]

XLM-RoBERTa Tokenizer loaded and 'Sub-Domain' data processed.
Sample of processed_datasets_xlm_roberta_sub_domain['train'][0]: {'input_ids': tensor([     0,  18336,  16460,   6155, 176997,    125,  59474,    896,  86517,
         16576,  72786, 206207, 135361,  41968, 168949,  19039, 162522,    999,
         34647,  11291,   4876, 215512, 167762,  33019, 145720, 153634,  16908,
         20824,  86517,  16576,  72786,  19039,   7443,   6638,   6386, 176997,
           999,  16447,  38841, 196695,    125,  22540,  38084,   2145,   6638,
         52431,  50442,   2763,      9,   9115,   2763,      9,   8276,   9307,
          8377,  16926,  10066, 100564,  12468,  29881,  54546,  24029,   4691,
         24373, 135361,  20134,  20824,  24373, 125506,    999,  21431,   4876,
           999,  25326,  27369,    999,   9853, 176997,    999, 203529,  63520,
         52730,  34647,  76675,  19039,  47458,  82712,  12468,  25326,    125,
             6,  98577,  14403,  23878,  30550,  58065, 155190, 176997,   4557,
        175142,  51001,   2801, 188434, 176997,  75770,   7277,  16550,  79911,
           125, 150430, 133998,   8099, 136418,    896,   8619, 188434,    125,
        185595,   4691, 152421,  72622,   4979,   8377,  26782,   8377,    896,
        186294,    896, 135241,  10066, 100564,    956, 165326,   5507,   8099,
        205665, 240178,   4822,  54546, 121542,  10413,   2937,  34916,   2784,
         21264, 161770, 135241,    999,  44056,  31696,  30010, 231964,   5507,
           125,  46275, 155190,  43710,   6386, 176997,   4557,      6,  90645,
          2145,   4480,   7185,   2801,  52431, 153634,  54682,   5534,   5780,
         25326,  80783,    125,  34995,  34653, 219695,  59474,    896,  86517,
         16576,  72786, 206207, 135361,  46930,  26448, 231825, 215512,  80249,
          9976, 115635, 125506,   6638,  44201,   9307,    125,      2,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(10)}
Sample of processed_datasets_xlm_roberta_sub_domain['validation'][0]: {'input_ids': tensor([     0,  65081,  45397,  43497,   2937,  40256,    204,  44993,   7498,
          5534,  22349,    896,     26,   8619, 222321,  73923,  33237, 140590,
        118959,  42884,  12173,  40449, 125992,   2451,  81305,   9853,  13880,
          9115,   2784, 196512,    896,  35699,   8050,  59105,  57732,  44266,
         73378,   2451,  44993,  88585, 239904,      6, 154242,    125,  66468,
          4691,  38841,   9755,  54233,  98156, 240029,  43053,   7498,   8099,
        124132, 189742,    896, 188910, 148145,  12229,  69057,   5507, 140707,
           956,  14510, 232154, 239383, 215559, 139169,   9591,      4,  17830,
         45397,  26172,  27496,      6, 112542,   2937,  19039,  15541, 241012,
         12173,  10947, 125891,  84584,    125,  46729, 204361,    956,  46087,
         80783,      4, 194000,    999,  99982,  62429, 240029,    999, 227381,
         43497, 169311, 125992,   2114, 206494,    896,  44056,  51538, 231964,
           956, 242470,  45397,  17830,  23703,  57271,  19418,   4822,  92925,
          4480,    125,  66468,   4691,  38841,  74665,   2784, 118425,   2145,
        152585,  47193,  12173, 101311,   3718,  39267,  60902,    125,  32427,
        182347, 119226,      6, 100827,   9853,  56500,  12229,   4979, 207678,
          3458,   2145,  27372, 135654,  17589,   6638, 125992, 169311,    999,
        152585,  43014,  24029,  39994,    896,  23304, 227514, 209423,  54112,
           896,  62429,  98282,   2114,  82717,    896, 107913, 240029, 173427,
           125, 147890, 233880,  12173,  60914,  90599, 236829,      6,  64220,
         47458,   2145,  53207, 103265,  34653,   2937,  30511,      6,  64220,
         47458,   2145,  45543,   3397,  21264, 129451,   9681,      4, 217092,
        221189,  69233,  79866,      6,  54233,  89375,  94238,   9681,    125,
             6,  41758,  88585,  60914,  60902, 134826,  35312, 124132, 238965,
          9755,  20404,  17455, 240029,    999,   9755,   4822,   9618, 211556,
         40449,    125,  38254,  77065, 169311,  54112,  54112,  86135, 189742,
           896,  90599,      6, 106761, 230883,  80783,    125,  11785,   8339,
        125843,  34545,  40449,  14510, 236829,  82717,  34653, 147890,      6,
         64220,  47458,  31938, 234931,      6,  77485,  21436, 114505,  12814,
             4,  40256, 240330, 148047,   5507, 222321,  63094,  30747,   4480,
           125, 195470,   2730,   2801, 130711, 238763,    896,   7277,  42617,
          9618, 166404,  41894,  12814,      4, 168581, 155657,   6638,  53264,
        207809, 240029,  54682,  26564,    896,   8619,  99982,  26200,  14510,
         28445,   4557, 238965,  43053,   7498,   7185,  13171,      4,  20340,
         39680,   4557,   2730,  73431, 236829,  82717,    896, 107913,    125,
         11785,  21387, 169311,   1104,   3458, 130180,  39994,  64248,  31527,
         61280, 175142,  74252,   2451, 199837,   4557,  72238,   8377,      6,
        195138,  69641,  16550,  70904, 123258,  67159,  12229,  70866,  21820,
         11622,   2763, 147274,    999,  58123,      4, 200916,   4557,  92164,
          3718,  67972,  34523,  17891, 108126,   3718, 161951,  92984,  66519,
          7802,  72786, 224306,    896,  58123,    125,  46275,   7802,  72786,
        224306, 132336,   3397, 169311,    999,  93393,  39267,     74,      6,
         56415,  17031, 193170,      4,  44266, 209644,      4,  26596, 122187,
          2114,  14403,  19796,  24256,  82829,  43497,  34653,   2937,      6,
         64220,  47458,  31938, 138388,   5507,  63094,    999,  93393, 238965,
         45543,    956,  16926,  75004,    125, 169311,    999,  58123, 240029,
           999, 101894,   2801, 143892,  37783,  54112,  82717,    896, 217834,
        220291,   2730,  98282,   2114, 114269,  17145,  97826, 147344,     74,
        169311,    999, 198760,  38959,  38540,  12468,  26200,  82717,    896,
         73024,  88136,  64123,  34297,      4,  11785,  21387,  31527,  61280,
         30549,   4557, 236829,  82717,    125, 152585, 155190,  13327,   3397,
        135654,  23304,  23304, 169311,      6, 170025,   4691,  26172, 152461,
          6638,   7277,  15845, 112112,   3397,  25326, 112982,   2114, 155865,
           896,  23304,  61705,   9078,  77359, 239383, 203679, 221686, 123472,
         12814,    125,  22540,  93393,   2730, 169311,   2937, 212224,   7185,
        236829,  82717,  34653,   2937,  36147,    999,   3495, 125992,   4876,
         29881,   4557,   2763,  36775, 172477, 222503,    125,      2]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]), 'labels': tensor(13)}
Sample of processed_datasets_xlm_roberta_sub_domain['test'][0]: {'input_ids': tensor([     0,    345,  34014,      9,  77007,  21640,   1831,  79852, 124418,
            90,   2804,  18925,    442,     83,  82424, 172852,     10,  34390,
            71, 113014,  80889,  24189,  53333,  60322,  25632,     70,   2878,
           289,    456,  59636,    214,    111,  18150,   1831,  65421,      5,
            52,  73243,  28960,      7,     70,   2878,    289,    456,      9,
         59636,    214,    111,  18150,   1831,  65421,    100,     70,  46002,
         55080,    111,  60091, 113014,      7,      4,     63,     70,   1831,
          2256,   2804,     23,     10,   2450,  63805,      5,   2161,  11994,
           190,    136,    305,      4,   1286,   3501,    805, 113014,      7,
          1221,      8,  17365,   1295,  61069,    136,  30646,      4,  85358,
           214,  44828,  26255,     28,  33730,     47,  58359,   2363,   2704,
         78869,      7,    237,   5299,    237,  85590,  33362,   6044,    237,
           117,   4745,  19736,    136,      6, 163414,    329,     34,  70760,
             7,      4,     70,   1831,  79852,   2804,      5,    581,   1831,
          2256,   2843,   2804,    442,   2806, 128839,    538,    456, 177149,
          6863,  12403,    214,  80889,      4,  28368,     47,   1831,  65421,
           185,  25820,  41159,    136,    756,  41018,    289,  96679,   8035,
           435,      5,     52,   5464,  29362,     53,     83,  11343,   2446,
          2663,  25343,     53,      4,     63,     70,  63805,   2804,      4,
        154107,    450,     70,   1831,   2256, 136622,     47,  12983,     70,
         16648,    136,  39908,   6863,  41018,      7,  59499,    538,      5,
          1326,   5036,      4,  59463,    765,   2809, 115992,     71,     47,
        172337,     47,     70, 146619,   4734,   2174,   1836,    765,     10,
         39563,    297, 100124,      4, 124418,     90,   2804,      5,      2,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(12)}

In [ ]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import numpy as np
import pandas as pd

# 1. Get number of unique labels for the model's output layer for 'Sub-Domain' classification
# Retrieve number of classes directly from dataset
num_labels_sub_domain = int(nlp_df['Sub-Domain_ID'].nunique())
print(f"Number of unique labels for Sub-Domain classification: {num_labels_sub_domain}")

# 2. Load the pre-trained XLM-RoBERTa model for sequence classification
xlm_roberta_sub_domain_model = AutoModelForSequenceClassification.from_pretrained(
    xlm_roberta_sub_domain_model_name,
    num_labels=num_labels_sub_domain
)
print(f"Model '{xlm_roberta_sub_domain_model_name}' loaded for Sub-Domain classification.")

# 3. Define evaluation metrics
def compute_metrics(eval_pred):
    labels = eval_pred.label_ids
    preds = eval_pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro', zero_division=0)
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# 4. Configure training arguments for Sub-Domain classification
training_args_xlm_roberta_sub_domain = TrainingArguments(
    output_dir='./results_xlm_roberta_sub_domain',
    num_train_epochs=10,
    per_device_train_batch_size=16,         # Increased for L4 GPU
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    learning_rate=2e-5,                     # Added learning rate
    # logging_dir='./logs_xlm_roberta_sub_domain',
    logging_steps=10,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    fp16=use_cuda,                           # Enable mixed precision only if GPU is available
    report_to='none'
)

# 5. Initialize the Trainer for Sub-Domain classification
trainer_xlm_roberta_sub_domain = Trainer(
    model=xlm_roberta_sub_domain_model,
    args=training_args_xlm_roberta_sub_domain,
    train_dataset=processed_datasets_xlm_roberta_sub_domain['train'],
    eval_dataset=processed_datasets_xlm_roberta_sub_domain['validation'],
    compute_metrics=compute_metrics
)

print("Trainer initialized for XLM-RoBERTa Sub-Domain classification.")

# 6. Train the model
trainer_xlm_roberta_sub_domain.train()

print("XLM-RoBERTa Sub-Domain classification training complete. Evaluating model on the test set.")

# 7. Evaluate the model on the test set
results_xlm_roberta_sub_domain = trainer_xlm_roberta_sub_domain.evaluate(processed_datasets_xlm_roberta_sub_domain['test'])

print("XLM-RoBERTa Sub-Domain classification Test set evaluation results:")
for key, value in results_xlm_roberta_sub_domain.items():
    print(f"  {key}: {value:.4f}")

# 8. Create a pandas DataFrame for XLM-RoBERTa's Sub-Domain classification metrics
xlm_roberta_sub_domain_metrics_data = {
    'Model': ['XLM-RoBERTa (Sub-Domain_Flat)'],
    'Accuracy': [results_xlm_roberta_sub_domain['eval_accuracy']],
    'Precision (Macro Avg)': [results_xlm_roberta_sub_domain['eval_precision']],
    'Recall (Macro Avg)': [results_xlm_roberta_sub_domain['eval_recall']],
    'F1-Score (Macro Avg)': [results_xlm_roberta_sub_domain['eval_f1']]
}
xlm_roberta_sub_domain_metrics_df = pd.DataFrame(xlm_roberta_sub_domain_metrics_data)

# 9. Display the xlm_roberta_sub_domain_metrics_df DataFrame
display(xlm_roberta_sub_domain_metrics_df)

Number of unique labels for Sub-Domain classification: 15

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model 'xlm-roberta-base' loaded for Sub-Domain classification.
Trainer initialized for XLM-RoBERTa Sub-Domain classification.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

XLM-RoBERTa Sub-Domain classification training complete. Evaluating model on the test set.

XLM-RoBERTa Sub-Domain classification Test set evaluation results:
  eval_loss: 0.9440
  eval_accuracy: 0.8135
  eval_f1: 0.8103
  eval_precision: 0.8106
  eval_recall: 0.8121

,Model,Accuracy,Precision (Macro Avg),Recall (Macro Avg),F1-Score (Macro Avg)
0,XLM-RoBERTa (Sub-Domain_Flat),0.813528,0.810599,0.812077,0.810321

## Sub-domain Train Loss

In [ ]:
import plotly.graph_objects as go
import pandas as pd

def plot_interactive_loss(trainer, title):
    # Extract log history
    history = trainer.state.log_history

    train_loss = [entry for entry in history if 'loss' in entry and 'epoch' in entry]
    val_loss = [entry for entry in history if 'eval_loss' in entry and 'epoch' in entry]

    df_train = pd.DataFrame(train_loss)
    df_val = pd.DataFrame(val_loss)

    fig = go.Figure()

    # Add Training Loss Trace
    if not df_train.empty:
        fig.add_trace(go.Scatter(
            x=df_train['epoch'],
            y=df_train['loss'],
            mode='lines+markers',
            name='Training Loss',
            line=dict(color='blue')
        ))

    # Add Validation Loss Trace
    if not df_val.empty:
        fig.add_trace(go.Scatter(
            x=df_val['epoch'],
            y=df_val['eval_loss'],
            mode='lines+markers',
            name='Validation Loss',
            line=dict(color='red', dash='dash')
        ))

    fig.update_layout(
        title=f'Interactive Loss Curve: {title}',
        xaxis_title='Epochs',
        yaxis_title='Loss',
        template='plotly_white',
        hovermode='x unified'
    )

    fig.show()

# Generating Interactive Graph only for Sub-Domain Model
print("Generating Interactive Loss Graph for Sub-Domain Model...")
plot_interactive_loss(trainer_xlm_roberta_sub_domain, "Sub-Domain Classification (XLM-RoBERTa)")

Generating Interactive Loss Graph for Sub-Domain Model...

In [ ]:
import torch

# Create mappings from ID to Name for Domain and Sub-Domain
domain_id_to_name = nlp_df[['Domain_ID', 'Domain']].drop_duplicates().set_index('Domain_ID')['Domain'].to_dict()
sub_domain_id_to_name = nlp_df[['Sub-Domain_ID', 'Sub-Domain']].drop_duplicates().set_index('Sub-Domain_ID')['Sub-Domain'].to_dict()

print("Domain ID to Name Mapping:", domain_id_to_name)
print("Sub-Domain ID to Name Mapping:", sub_domain_id_to_name)

# Mount Google Drive
We will mount Google Drive to save the models and pickle files directly into your personal drive storage.

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# # Define the target directory in Google Drive
# save_dir = '/content/drive/MyDrive/xlm_roberta_domain_model'
# os.makedirs(save_dir, exist_ok=True)
# print(f"Directory created or verified at: {save_dir}")

### Save the Trained Model, Tokenizer and Mappings
Now we will save the XLM-RoBERTa domain model and its tokenizer using their built-in `save_pretrained` method, and use `pickle` to export our class mapping dictionaries (`domain_id_to_name` and `sub_domain_id_to_name`).

In [ ]:
import os
import pickle

# Define directories to save models, tokenizers, and mappings
save_dir_domain = '/content/drive/MyDrive/Cross/Domain/Cross-xlm-domain'
save_dir_sub_domain = '/content/drive/MyDrive/Cross/SUb-Domain/Cross-xlm-sub-domain'

# Create directories if they don't exist
os.makedirs(save_dir_domain, exist_ok=True)
os.makedirs(save_dir_sub_domain, exist_ok=True)

# Save the Domain classification model, tokenizer, and mappings
xlm_roberta_domain_model.save_pretrained(save_dir_domain)
xlm_roberta_domain_tokenizer.save_pretrained(save_dir_domain)
with open(os.path.join(save_dir_domain, 'domain_id_to_name.pkl'), 'wb') as f:
    pickle.dump(domain_id_to_name, f)
print(f"Domain model, tokenizer, and mappings saved to: {save_dir_domain}")

# Save the Sub-Domain classification model, tokenizer, and mappings
xlm_roberta_sub_domain_model.save_pretrained(save_dir_sub_domain)
xlm_roberta_sub_domain_tokenizer.save_pretrained(save_dir_sub_domain)
with open(os.path.join(save_dir_sub_domain, 'sub_domain_id_to_name.pkl'), 'wb') as f:
    pickle.dump(sub_domain_id_to_name, f)
print(f"Sub-Domain model, tokenizer, and mappings saved to: {save_dir_sub_domain}")

#Predictions

In [ ]:
def predict_domain_and_sub_domain(text):
    # Determine the device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Predict Domain
    inputs_domain = xlm_roberta_domain_tokenizer(text, return_tensors='pt', truncation=True, padding='max_length', max_length=MAX_LENGTH_DOMAIN)
    # Move input tensors to the same device as the model
    inputs_domain = {k: v.to(device) for k, v in inputs_domain.items()}

    # Move the model to the device if it's not already there (this should ideally be done once during model loading)
    xlm_roberta_domain_model.to(device)

    with torch.no_grad():
        outputs_domain = xlm_roberta_domain_model(**inputs_domain)
    predicted_domain_id = torch.argmax(outputs_domain.logits, dim=-1).item()
    predicted_domain = domain_id_to_name.get(predicted_domain_id, "Unknown Domain")

    # Prepare input for Sub-Domain prediction. Based on your clarification,
    # the sub-domain model was trained individually on 'Text' only (flat classification).
    # So, we only use the original text for sub-domain prediction.
    sub_domain_input_text = text # Changed from: predicted_domain + " " + text

    # Predict Sub-Domain
    inputs_sub_domain = xlm_roberta_sub_domain_tokenizer(sub_domain_input_text, return_tensors='pt', truncation=True, padding='max_length', max_length=MAX_LENGTH_SUB_DOMAIN)
    # Move input tensors to the same device as the model
    inputs_sub_domain = {k: v.to(device) for k, v in inputs_sub_domain.items()}

    # Move the model to the device if it's not already there (this should ideally be done once during model loading)
    xlm_roberta_sub_domain_model.to(device)

    with torch.no_grad():
        outputs_sub_domain = xlm_roberta_sub_domain_model(**inputs_sub_domain)
    predicted_sub_domain_id = torch.argmax(outputs_sub_domain.logits, dim=-1).item()
    predicted_sub_domain = sub_domain_id_to_name.get(predicted_sub_domain_id, "Unknown Sub-Domain")

    return predicted_domain, predicted_sub_domain

print("Prediction function 'predict_domain_and_sub_domain' defined.")

### Prediction Demonstration
Let's test the `predict_domain_and_sub_domain` function with a sample text.

In [ ]:
sample_text = '''
The Ministry of Commerce has granted permission to import 150,000 tonnes of crude salt ahead of the new production season. Officials from the Bangladesh Small and Cottage Industries Corporation (BSCIC) stated that this import was recommended due to fears of a potential shortage.
However, salt farmers are aggrieved by the Ministry of Commerce's decision. They claim there is no salt shortage in the country. Permission for imports was granted just as farmers—after months of losses—were beginning to see some profit.
According to BSCIC data, the total demand for refined salt in the country for the 2026–27 fiscal year is estimated at 2.1 million tonnes. This includes 750,000 tonnes of edible salt, 950,000 tonnes for industrial use, 37,000 tonnes for fish farming, and 306,000 tonnes for the livestock sector. The salt production season in the country typically runs from November to May.
Sarwar Hossain, head of BSCIC’s salt cell, told *Prothom Alo* that production was somewhat lower last season. Currently, there are 490,000 tonnes of salt in stock at the field level and 177,000 tonnes at mills. The country's monthly demand is approximately 220,000 tonnes; at this rate, current stocks will last until mid-December. Salt from the new season will begin arriving before then. However, production was very low during the first two months of last season. Based on that experience, the import recommendation was made to avert a potential shortage lasting 20 to 25 days.
On the other hand, senior officials from several salt mills argue that permission to import salt is granted almost every year citing fears of a shortage. Permission was granted last year as well but was later cancelled; no market crisis occurred even without the imports. They allege that permission to import crude salt is granted to benefit a specific group of mill owners. Ultimately, the import permits are sold at high prices, and the market price of salt rises.
Currently, there are 490,000 tonnes of salt in stock at the field level and 177,000 tonnes at mills. The country's monthly demand is approximately 220,000 tonnes.
AJM Siam, General Secretary of the Bangladesh Salt Farmers' Welfare Council, stated that the production cost per *maund* (approx. 37.3 kg) of salt last season was between Tk 320 and Tk 330. At the beginning of the season, farmers sold salt at a loss of Tk 40 to 50 per maund. Prices began to rise towards the end of the season; currently, with sales at Tk 380 per maund, they are finally seeing some profit. Granting import permission at this juncture would cause prices to drop.
There are a total of 251 salt mills across the country, located in Dhaka, Narayanganj, Chandpur, Chattogram, Patiya, Cox's Bazar, Khulna, and Jhalakathi. Among them, seven are modern vacuum mills: ACI Salt, Molla Salt, Triple Refinery Industries, Confidence Salt, City Group, Meghna Group of Industries, and SA Salt. These companies control 70 percent of the market for edible and industrial salt.
Inquiries reveal that, following lobbying by leaders of the Bangladesh Salt Mill Owners Association, BSCIC recommended salt imports in the middle of this year. Accordingly, the Ministry of Commerce granted permission last Monday to import 150,000 tonnes of crude salt.
Under this permission, 244 mills have been allowed to import a total of 132,500 tonnes (543 tonnes each), while the seven vacuum-process salt-producing companies have been permitted to import a total of 17,500 tonnes (2,500 tonnes each). However, it has been reported that 86 of the 244 mills did not produce any edible salt between July of last year and August of this year.
Nurul Kabir, President of the Bangladesh Salt Mill Owners Association, stated that one cannot practice discrimination when running an organization. He added that the government granted import permission to avert the risk of a crisis.
Sarwar Hossain, head of BSCIC’s salt cell, noted that in the past, many mill owners had gone to court over allocations based on production capacity—incidents that occurred twice previously. He warned that this time, if anyone sells their import permit, their registration will be cancelled.
'''
predicted_domain, predicted_sub_domain = predict_domain_and_sub_domain(sample_text)

print(f"Sample Text: {sample_text}")
print(f"Predicted Domain: {predicted_domain}")
print(f"Predicted Sub-Domain: {predicted_sub_domain}")

sample_text_2 = '''সাবেক আইনমন্ত্রী আনিসুল হকসহ ৪ জনের বিরুদ্ধে ১৭২ কোটি ২৪ লাখ ৩২ হাজার ৯৪১ টাকার ‘অবৈধ সম্পদ’ অর্জন এবং ৭৩৭ কোটি ২৪ লাখ ২৬ হাজার ৫৮১ টাকার ‘অস্বাভাবিক ও সন্দেহজনক’ লেনদেনের প্রমাণ পাওয়ার কথা জানিয়েছে দুর্নীতি দমন কমিশন (দুদক)। বুধবার এই চারজনের বিরুদ্ধে আদালতে অভিযোগপত্র দাখিলের অনুমোদন দিয়েছে সংস্থাটি।
মামলার অপর তিন আসামি হলেন আনিসুল হকের ছোট ভাইয়ের স্ত্রী জেবুন্নেসা বেগম হক কলি, ভাগনে শেখ মো. ইফতেখারুল ইসলাম ও ‘কাজিন’ হিসেবে পরিচিত মোহাম্মদ ইকবাল। দুদক সচিব মো. সাইদুর রহমান খান এক সংবাদ সম্মেলনে বলেন, এই তিনজন আনিসুল হককে অবৈধ সম্পদ অর্জনে প্রত্যক্ষ ও পরোক্ষভাবে সহায়তা করেছেন।
দুদকের তদন্তে আনিসুল হকের গ্রহণযোগ্য আয় পাওয়া গেছে ১৩ কোটি ২৭ লাখ ৯৫ হাজার ২৩৮ টাকা। এর বিপরীতে পারিবারিক ব্যয় ধরা হয়েছে ৪ কোটি ৬৬ লাখ ৫৪ হাজার ২৯৮ টাকা। ব্যয় বাদে নিট সঞ্চয় দাঁড়ায় ৮ কোটি ৬১ লাখ ৪০ হাজার ৯৪০ টাকা। অন্যদিকে আনিসুল হক ও অপর তিন আসামির নামে মোট ১৮০ কোটি ৮৫ লাখ ৭৩ হাজার ৮৮১ টাকার সম্পদ থাকার তথ্য পেয়েছে দুদক। গ্রহণযোগ্য নিট আয় বাদ দিলে ১৭২ কোটি ২৪ লাখ ৩২ হাজার ৯৪১ টাকার সম্পদকে ‘জ্ঞাত আয়ের উৎসের সঙ্গে অসংগতিপূর্ণ’ বলেছে সংস্থাটি।
দুদকের ভাষ্য, ২০০০ সালের ৩০ জুন থেকে ২০২৬ সালের ১৯ জুলাই পর্যন্ত সময়ে এসব সম্পদ অর্জিত হয়েছে। আনিসুল হকের নিজের নামে ৯৬ কোটি ৮০ লাখ ৬৬ হাজার ৮৮০ টাকার স্থাবর-অস্থাবর সম্পদ রয়েছে। অপর তিনজনের নামে রয়েছে ৮৪ কোটি ৫ লাখ ৭ হাজার ১ টাকার সম্পদ।
২৩ ব্যাংক হিসাবে ৭৩৭ কোটি টাকার লেনদেন|আনিসুল হক ও তাঁর স্বার্থসংশ্লিষ্ট ব্যক্তি ও প্রতিষ্ঠানের ২৩টি ব্যাংক হিসাবে মোট ৩৭৫ কোটি ৫০ লাখ ৯৯ হাজার ৪৫২ টাকা জমা এবং ৩৬১ কোটি ৭৩ লাখ ২৭ হাজার ১২৯ টাকা উত্তোলনের তথ্য পেয়েছে দুদক। জমা ও উত্তোলন মিলিয়ে মোট লেনদেনের পরিমাণ ৭৩৭ কোটি ২৪ লাখ ২৬ হাজার ৫৮১ টাকা।
দুদকের সন্দেহ, ‘দুর্নীতি ও ঘুষের মাধ্যমে’ পাওয়া অর্থের অবৈধ উৎস গোপন, রূপান্তর ও হস্তান্তরের উদ্দেশ্যে এসব লেনদেন করা হয়েছে।
২০২৫ সালের ১ জানুয়ারি আনিসুল হকের বিরুদ্ধে মামলাটি করেন দুদকের উপপরিচালক মো. জাহাঙ্গীর আলম। এজাহারে ১৪৬ কোটি ১৯ লাখ টাকার অবৈধ সম্পদ এবং ২৯টি ব্যাংক হিসাবে প্রায় ৬৬৬ কোটি টাকার লেনদেনের অভিযোগ ছিল।
অভিযোগপত্রে দুর্নীতি দমন কমিশন আইন, দুর্নীতি প্রতিরোধ আইন ও মানি লন্ডারিং প্রতিরোধ আইনের বিভিন্ন ধারার পাশাপাশি অপরাধে সহায়তা বা প্ররোচনার দায়ে দণ্ডবিধির ১০৯ ধারাও যুক্ত করা হয়েছে।
'''
predicted_domain_2, predicted_sub_domain_2 = predict_domain_and_sub_domain(sample_text_2)

print(f"\nSample Text: {sample_text_2}")
print(f"Predicted Domain: {predicted_domain_2}")
print(f"Predicted Sub-Domain: {predicted_sub_domain_2}")